--where clause kan toegevoegd worden om filteren mogelijk te maken
SELECT NAKIJKMODELVERSIE, VRAAGID, VRAAGVERSIE, CORRECTEANTWOORDEN, NAKIJKINSTRUCTIES
FROM NAKIJKMODEL
WHERE NAKIJKMODELVERSIE = ? OR VRAAGID = ? OR VRAAGVERSIE = ?