--where clause kan toegevoegd worden om filteren mogelijk te maken
SELECT STUDENTNUMMER, TENTAMENCODE, TENTAMENVERSIE, CIJFER, HASH    --BEOORDELENDEDOCENT
FROM RESULTAAT
WHERE  STUDENTNUMMER = ? OR TENTAMENCODE = ? OR TENTAMENVERSIE = ?