--where clause kan toegevoegd worden om filteren mogelijk te maken
SELECT VRAAGID, VRAAGVERSIE, STUDENTNUMMER, TENTAMENCODE, TENTAMENVERSIE, ANTWOORD, BEHAALDEPUNTEN, NAKIJKCOMMENT
FROM ANTWOORD_OP_VRAAG
WHERE ? = ?