
INSERT INTO VRAAG(VRAAGID, VRAAGVERSIE, VRAAGNAAM, VRAAGTYPE, VRAAGTHEMA, VRAAGCORRECTEANTWOORDEN, VRAAGNAKIJKINSTRUCTIES, NAKIJKMODELVERSIE, VRAAGSTELLING, VRAAGVERSIEDATUM, VRAAGVERSIEOMSCHRIJVING)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
