
INSERT INTO VRAAG(VRAAGID, VRAAGVERSIE, THEMANAAM, NAKIJKMODELVERSIE, VRAAGSTELLING, VRAAGPLUGIN, VRAAGOEFENVRAAG, VRAAGGEMAAKTDOOR, VRAAGVERSIEDATUM, VRAAGVERSIEOMSCHRIJVING)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
