
INSERT INTO TENTAMEN_MOMENT(TENTAMENMOMENTID, TENTAMENCODE, TENTAMENVERSIENUMMER, TENTAMENMOMENTDATUM, TENTAMENMOMENTBEGINTIJD,
  TENTAMENMOMENTEINDTIJD, TENTAMENMOMENTLOKALEN, TENTAMENMOMENTSLEUTEL, TENTAMENMOMENTTOEGESTANEHULPMIDDELEN,
  TENTAMENMOMENTBIJZONDERHEDEN)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)