UPDATE ANTWOORD_OP_VRAAG
SET VRAAGID = ?, VRAAGVERSIE = ?, STUDENTNUMMER = ?, TENTAMENCODE = ?, TENTAMENVERSIE = ?, ANTWOORD = ?, BEHAALDEPUNTEN = ?, NAKIJKCOMMENT = ?
WHERE VRAAGID = ? AND VRAAGVERSIE = ? AND STUDENTNUMMER = ? AND TENTAMENCODE = ? AND TENTAMENVERSIE = ?